var lang = {
'id': '1',
'language_code': 'ru',
'language_charset': 'windows-1251',
'fav_save': 'Нажмите Ctrl+D чтобы добавить страницу в закладки',
'sets_save': 'Сохранение настроек...',
'str_fail_serv': 'Отсутствует связь с сервером',
'sets_save_ok': 'Изменения сохранены',
'sets_save_fail': 'Произошла ошибка',
'str_fail_con': 'Отсутствует подключение',
'str_goto_exch': 'Открыть обменник',
'info_exch_verify': 'Данный обменный пункт прошел дополнительную проверку',
'info_exch_company': 'Данный обменный пункт имеет официальную юридическую регистрацию',
'details_rating': 'Рейтинг обменника',
'notify_tg_linked': 'Аккаунт Telegram привязан. Нажмите, чтобы сменить',
'notify_tg_link': '<установить>',
'notify_tg_howto_link': 'Запустите десктопную версию Telegram, перейдите по ссылке и в окне чата нажмите кнопку Start',
'notify_send': 'Отправка заявки...',
'notify_success': 'Заявка подана успешно',
'notify_error': 'Ошибка ввода',
'notify_error_det': 'Пожалуйста, исправьте следующие ошибки',
'notify_fail': 'Произошла ошибка. Обратитесь к администратору',
'notify_fail_serv': 'Сервер временно недоступен',
'str_ajax_title': 'Ждите...',
'contact_err_text': 'Введите текст сообщения',
'contact_email_request': 'Укажите ваш e-mail, если необходим ответ от нас:',
'contact_agree_need': 'Необходимо дать согласие с политикой конфиденциальности',
'contact_noemail': 'Не указан e-mail. Вы действительно хотите просто отправить сообщение, не получая на него ответ?',
'contact_unklang': 'Наша служба поддержки принимает письма и отвечает на только на русском и английском языках. Вы все равно желаете отправить это письмо?',
'blogger_agr1_need': 'Неоходимо подтвердить, что вы представитель ресурса',
'contact_send': 'Отправка сообщения...',
'contact_success': 'Отправлено успешно',
'contact_fail': 'Сообщение не отправлено',
'addto_soc_facebook': 'Facebook',
'addto_soc_twitter': 'Twitter',
'addto_soc_google': 'Закладки Google',
'addto_soc_vkontakte': 'ВКонтакте',
'addto_soc_yandex': 'Яндекс.Закладки',
'addto_title': 'Добавить в',
'bonus_button': 'Получить бонус',
'aff_main_captcha': '&larr; Нажмите для проверки',
'bonus_button_left': 'Осталось',
'aff_main_captcha_suc': 'Проверено успешно',
'bonus_frame': 'Чтобы получить бонус, необходимо открыть мониторинг обменников в отдельном окне',
'bonus_ok_desc': '<p>Если вам понравился мониторинг обменников BestChange, вы можете:</p><ul><li>Написать свой отзыв на <a target="_blank" rel="noreferrer" href="https://www.trustpilot.com/review/www.bestchange.com?languages=ru">Trustpilot</a> или во <a target="_blank" href="https://vk.com/topic-53507345_39091228">ВКонтакте</a> (мы очень любим получать отзывы);</li><li><a href="/partner/">Зарегистрироваться</a> в нашей реферальной программе и зарабатывать деньги, <span class="videolink" onclick="show_video(\'aff-ru\')"><span class="videoicon"></span><span class="link dashlink">рекламируя</span></span> BestChange;</li><li>Посоветовать BestChange вашим друзьям и знакомым;</li><li>Подписаться на наш канал в <a target="_blank" href="https://t.me/s/bestchangerus">Телеграм</a>.</li></ul>',
'bonus_thanks': 'Спасибо! Я хочу еще!',
'bonus_request_confirm': 'Вы уверены, что хотите получить выплату на кошелек?',
'bonus_request': 'Заказать выплату',
'bonus_request_send': 'Заказ выплаты...',
'bonus_satoshi': 'сатоши',
'tab_curr_expand': 'Развернуть полный список валют',
'tab_curr_reduce': 'Свернуть список валют, показать только популярные',
'info_frame': 'Чтобы оставить отзыв, откройте сайт в отдельном окне.',
'info_review_save': 'Добавление отзыва...',
'info_review_saved': 'Отзыв успешно сохранен',
'info_review_save_err': 'Ошибка добавления отзыва',
'info_review_delete': 'Удаление отзыва...',
'city_your': 'Ваш город',
'info_review_deleted': 'Отзыв удален',
'info_review_delete_err': 'Ошибка удаления',
'info_pass_verf': 'Проверка пароля...',
'info_pass_ok': 'Пароль верный',
'info_pass_inv': 'Неверный пароль',
'info_pass_verf_err': 'Ошибка проверки',
'city_find': 'Город или страна...',
'info_reviewpass': 'Пароль отзыва:',
'info_com_delete': 'Удалить',
'info_com_wrte': 'Написать',
'info_conf_del_review': 'Вы действительно хотите удалить этот отзыв?',
'info_claimtocancel': 'Снять претензию',
'info_claimtorenew': 'Возобновить претензию',
'info_com_save': 'Сохранение комментария...',
'info_com_saved': 'Комментарий опубликован',
'info_com_save_err': 'Ошибка отправки',
'info_com_turn': 'Свернуть',
'info_com_expand': 'Развернуть',
'fink_opt_rate_old': 'вместо заявленного',
'fink_opt_fee_old': 'вместо заявленной',
'fink_opt_mode_man': 'Ручной режим обмена вместо заявленного автоматического',
'fink_opt_mode_auto': 'Автоматический режим обмена вместо заявленного ручного',
'fink_send': 'Отправка информации...',
'fink_success': 'Благодарим за сотрудничество! Информация отправлена администратору',
'fink_fail': 'Информация не отправлена',
'favd_faved_link': 'Избранное',
'favd_faved_title': 'Удалить направление из списка Избранного',
'favd_link': 'Избранное',
'favd_title': 'Добавить направление в список Избранного для быстрого доступа',
'tabs_favd_desc': 'Избранные направления',
'tabs_top_desc': 'Популярные направления',
'exch_search': 'Для проверки уникальности введите название или домен обменного пункта:',
'exch_search_none': 'Похожие названия не найдены.',
'exch_search_found': 'Найдены проекты с созвучными названиями. Для уточнения информации, пожалуйста, обратитесь в администрацию мониторинга.',
'exch_search_err': 'Некорректный ввод. Попробуйте снова.',
'city_cur_geo': 'Текущее местоположение',
'str_km': 'км',
'info_review_check': 'Проверка безопасности...',
'info_review_disagree': 'Необходимо дать согласие с условиями BestChange',
'aml_report_started': 'Идет анализ адреса. Пожалуйста, ожидайте...',
'aml_report_almost': 'Данные получены, обновляем страницу...',
'aml_report_failed': 'Возникла ошибка. Пожалуйста, обратитесь к администратору.',
'pay_error': 'Ошибка получения реквизитов от криптопроцессинга. Пожалуйста, повторите попытку через полчаса, можно с тем же самым инвойсом. Если проблема повторится, пожалуйста, обратитесь в службу поддержки.',
'pay_arrived': 'Перевод поступил, оплата успешно завершена',
'aml_report_check': 'Уточнение статуса...',
'aml_report_waiting': 'Ожидание оплаты...',
'aml_voucher_check': 'Проверка и оплата...',
'str_fail_err': 'Произошла ошибка',
'aml_voucher_input': 'Пожалуйста, введите код ваучера'
};